const state={game:null,play:null,tracks:[],frame:0,timer:null,activeSource:null};
const $=id=>document.getElementById(id);
async function json(url,options){const r=await fetch(url,options);if(!r.ok)throw new Error(await r.text());return r.json()}
function field(){const c=$('field'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#1b673c';x.fillRect(0,0,c.width,c.height);x.strokeStyle='rgba(255,255,255,.8)';x.lineWidth=2;for(let yd=10;yd<=110;yd+=5){x.beginPath();x.moveTo(yd*10,0);x.lineTo(yd*10,c.height);x.stroke()}x.fillStyle='rgba(255,255,255,.9)';x.font='18px system-ui';for(let yd=20;yd<=100;yd+=10)x.fillText(String(yd<=60?yd-10:110-yd),yd*10-10,30)}
function draw(){field();const rows=state.tracks.filter(r=>Number(r.frame_id)===Number(state.frame));const c=$('field'),x=c.getContext('2d');for(const r of rows){x.beginPath();x.fillStyle=(r.team||'').toLowerCase().includes('home')?'#67d5ff':'#ffd166';x.arc(Number(r.x)*10,Number(r.y)*10,10,0,Math.PI*2);x.fill();x.fillStyle='#08110d';x.font='bold 12px system-ui';x.textAlign='center';x.fillText(r.jersey_number??'?',Number(r.x)*10,Number(r.y)*10+4)}const t=rows[0]?.t??0;$('clock').textContent=`${Number(t).toFixed(1)}s`;}
async function loadGames(){const games=await json('/api/games');$('games').innerHTML=games.map(g=>`<option value="${g.game_id}">${g.game_id}</option>`).join('');if(games.length){state.game=games[0].game_id;await loadPlays()}}
async function loadPlays(){state.game=$('games').value;const plays=await json(`/api/games/${state.game}/audit-queue?limit=30`);$('plays').innerHTML='';let first=null;for(const p of plays){const b=document.createElement('button');b.className=`play ${p.processing_status||''}`;b.innerHTML=`<small>Q${p.quarter??'?'} ${p.clock??''} · ${p.down_no??'?'} & ${p.distance??'?'}</small>${p.description}<small>Review: ${(p.review_reasons||[]).join(' · ')}</small>`;b.onclick=()=>selectPlay(p,b);$('plays').appendChild(b);if(!first)first=[p,b]}$('status').textContent=plays.length?`${plays.length} important reviews queued`:'Important review queue is clear';if(first)await selectPlay(first[0],first[1])}
function sourceStart(source){return Number(source.snap_s??source.start_s)}
function sourceEnd(source){return Number(source.play_end_s??source.end_s)}
function seekSource(source,button){const film=$('film');state.activeSource=source;document.querySelectorAll('.sources button').forEach(x=>x.classList.remove('active'));button?.classList.add('active');const seek=()=>{film.currentTime=sourceStart(source);film.play()};if(film.readyState>=1)seek();else film.addEventListener('loadedmetadata',seek,{once:true})}
function loadTimingSource(){const sources=state.play?.sources||[],source=sources[Number($('timing-source').value)||0];if(!source)return;$('timing-snap').value=source.snap_s??source.start_s;$('timing-end').value=source.play_end_s??source.end_s}
async function selectPlay(p,button){document.querySelectorAll('.play').forEach(x=>x.classList.remove('active'));button.classList.add('active');state.play=p;state.tracks=[];state.activeSource=null;$('play-title').textContent=`Q${p.quarter??'?'} ${p.clock??''} — ${p.possession??''}`;$('play-detail').textContent=p.description;$('diagnostics').textContent=JSON.stringify({status:p.processing_status,reasons:p.reasons,metrics:p.metrics},null,2);$('film').src=`/api/video/${state.game}`;const sources=p.sources||[];$('sources').innerHTML='';let firstButton=null;for(const [i,source] of sources.entries()){const b=document.createElement('button');if(!firstButton)firstButton=b;b.textContent=`Source ${i+1} · ${source.angle} · ${(sourceEnd(source)-sourceStart(source)).toFixed(1)}s action`;b.onclick=()=>seekSource(source,b);$('sources').appendChild(b)}if(sources.length)seekSource(sources[0],firstButton);$('timing').hidden=!sources.length;$('timing-source').innerHTML=sources.map((s,i)=>`<option value="${i}">Source ${i+1} · ${s.angle}</option>`).join('');$('timing-status').textContent='';loadTimingSource();const audit=p.audit||{};$('audit').hidden=!audit.selected;$('audit-mapping').checked=audit.mapping_correct===1;$('audit-sources').checked=audit.sources_correct===1;$('audit-timing').checked=audit.timing_correct===1;$('audit-notes').value=audit.notes||'';$('audit-status').textContent='';if(p.play_id){try{state.tracks=await json(`/api/plays/${p.play_id}/tracks`)}catch{} }const ids=[...new Set(state.tracks.map(r=>Number(r.frame_id)))].sort((a,b)=>a-b);$('timeline').min=ids[0]??0;$('timeline').max=ids.at(-1)??0;$('timeline').value=ids[0]??0;state.frame=Number($('timeline').value);draw()}
$('film').addEventListener('timeupdate',()=>{if(state.activeSource&&$('film').currentTime>=sourceEnd(state.activeSource)){ $('film').pause();$('film').currentTime=sourceEnd(state.activeSource)}});
$('audit-save').onclick=async()=>{if(!state.play?.play_id)return;$('audit-status').textContent='Saving…';try{await json(`/api/plays/${state.play.play_id}/audit`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({mapping_correct:$('audit-mapping').checked,sources_correct:$('audit-sources').checked,timing_correct:$('audit-timing').checked,notes:$('audit-notes').value})});await loadPlays()}catch(e){$('audit-status').textContent=e.message}};
$('timing-source').onchange=loadTimingSource;$('timing-save').onclick=async()=>{const index=Number($('timing-source').value)||0,source=state.play?.sources?.[index];if(!source)return;$('timing-status').textContent='Saving…';try{const result=await json(`/api/clips/${encodeURIComponent(source.clip_id)}/timing`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({snap_s:Number($('timing-snap').value),play_end_s:Number($('timing-end').value)})});source.snap_s=result.snap_s;source.play_end_s=result.play_end_s;$('timing-status').textContent='Saved'}catch(e){$('timing-status').textContent=e.message}};
$('games').onchange=loadPlays;$('timeline').oninput=e=>{state.frame=Number(e.target.value);draw()};$('play-animation').onclick=()=>{if(state.timer){clearInterval(state.timer);state.timer=null;return}state.timer=setInterval(()=>{state.frame++;if(state.frame>Number($('timeline').max)){clearInterval(state.timer);state.timer=null;return}$('timeline').value=state.frame;draw()},100)};field();loadGames().catch(e=>$('status').textContent=e.message);
