const state={game:null,play:null,tracks:[],frame:0,timer:null,activeSource:null};
const $=id=>document.getElementById(id);
async function json(url){const r=await fetch(url);if(!r.ok)throw new Error(await r.text());return r.json()}
function field(){const c=$('field'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#1b673c';x.fillRect(0,0,c.width,c.height);x.strokeStyle='rgba(255,255,255,.8)';x.lineWidth=2;for(let yd=10;yd<=110;yd+=5){x.beginPath();x.moveTo(yd*10,0);x.lineTo(yd*10,c.height);x.stroke()}x.fillStyle='rgba(255,255,255,.9)';x.font='18px system-ui';for(let yd=20;yd<=100;yd+=10)x.fillText(String(yd<=60?yd-10:110-yd),yd*10-10,30)}
function draw(){field();const rows=state.tracks.filter(r=>Number(r.frame_id)===Number(state.frame));const c=$('field'),x=c.getContext('2d');for(const r of rows){x.beginPath();x.fillStyle=(r.team||'').toLowerCase().includes('home')?'#67d5ff':'#ffd166';x.arc(Number(r.x)*10,Number(r.y)*10,10,0,Math.PI*2);x.fill();x.fillStyle='#08110d';x.font='bold 12px system-ui';x.textAlign='center';x.fillText(r.jersey_number??'?',Number(r.x)*10,Number(r.y)*10+4)}const t=rows[0]?.t??0;$('clock').textContent=`${Number(t).toFixed(1)}s`;}
async function loadGames(){const games=await json('/api/games');$('games').innerHTML=games.map(g=>`<option value="${g.game_id}">${g.game_id}</option>`).join('');if(games.length){state.game=games[0].game_id;await loadPlays()}}
async function loadPlays(){state.game=$('games').value;const plays=await json(`/api/games/${state.game}/plays`);$('plays').innerHTML='';for(const p of plays){const b=document.createElement('button');b.className=`play ${p.processing_status||''}`;b.innerHTML=`<small>Q${p.quarter??'?'} ${p.clock??''} · ${p.down_no??'?'} & ${p.distance??'?'}</small>${p.description}`;b.onclick=()=>selectPlay(p,b);$('plays').appendChild(b)}$('status').textContent=`${plays.length} eligible plays`}
function seekSource(source,button){const film=$('film');state.activeSource=source;document.querySelectorAll('.sources button').forEach(x=>x.classList.remove('active'));button?.classList.add('active');const seek=()=>{film.currentTime=Number(source.start_s);film.play()};if(film.readyState>=1)seek();else film.addEventListener('loadedmetadata',seek,{once:true})}
async function selectPlay(p,button){document.querySelectorAll('.play').forEach(x=>x.classList.remove('active'));button.classList.add('active');state.play=p;state.tracks=[];state.activeSource=null;$('play-title').textContent=`Q${p.quarter??'?'} ${p.clock??''} — ${p.possession??''}`;$('play-detail').textContent=p.description;$('diagnostics').textContent=JSON.stringify({status:p.processing_status,reasons:p.reasons,metrics:p.metrics},null,2);$('film').src=`/api/video/${state.game}`;const sources=p.sources||[];$('sources').innerHTML='';let firstButton=null;for(const [i,source] of sources.entries()){const b=document.createElement('button');if(!firstButton)firstButton=b;b.textContent=`Source ${i+1} · ${source.angle} · ${(source.end_s-source.start_s).toFixed(1)}s`;b.onclick=()=>seekSource(source,b);$('sources').appendChild(b)}if(sources.length)seekSource(sources[0],firstButton);if(p.play_id){try{state.tracks=await json(`/api/plays/${p.play_id}/tracks`)}catch{} }const ids=[...new Set(state.tracks.map(r=>Number(r.frame_id)))].sort((a,b)=>a-b);$('timeline').min=ids[0]??0;$('timeline').max=ids.at(-1)??0;$('timeline').value=ids[0]??0;state.frame=Number($('timeline').value);draw()}
$('film').addEventListener('timeupdate',()=>{if(state.activeSource&&$('film').currentTime>=Number(state.activeSource.end_s)){ $('film').pause();$('film').currentTime=Number(state.activeSource.end_s)}});
$('games').onchange=loadPlays;$('timeline').oninput=e=>{state.frame=Number(e.target.value);draw()};$('play-animation').onclick=()=>{if(state.timer){clearInterval(state.timer);state.timer=null;return}state.timer=setInterval(()=>{state.frame++;if(state.frame>Number($('timeline').max)){clearInterval(state.timer);state.timer=null;return}$('timeline').value=state.frame;draw()},100)};field();loadGames().catch(e=>$('status').textContent=e.message);
